### ISSUE TITLE
conflict in monetary_value calculation and definition

### ISSUE THREAD

**Issue by kurtsenol** [ColtAllen/btyd#56]
The definition for monetary_value in the document:
"monetary_value represents the average value of a given customer’s purchases. This is equal to the sum of all a customer’s purchases divided by the total number of purchases. Note that the denominator here is different than the frequency described above."

summary_data_from_transaction_data function calculates monetary value as the mean of repeat purchases which equals to frequency.

**Comment by ColtAllen** [comment]
Hey @kurtsenol,

After further review I've determined this to be a bug in the pre-fork legacy code, so thanks for bringing it to my attention.

The research paper clearly defines monetary value as a customer's average transaction value across all transactions:

https://www.brucehardie.com/notes/025/gamma_gamma.pdf

However, `summary_data_from_transaction_data` (and by extension, `calibration_and_holdout_data`) are omitting the first transaction from the monetary value calculations:

https://github.com/CamDavidsonPilon/lifetimes/issues/429

In addition, frequency is being calculated as the count of time periods when repeat transactions occurred, rather than the count of all repeat transactions. This means a customer could make multiple transactions in a single time period and it would only be treated as a single transaction, which goes against the definition of frequency in every paper I've read and is also highly disruptive to monetary value calculations as illustrated in the above weblink.

I'll start working on this for the next version release, but until it's published I would advise against using the `summary_data_from_transaction_data` and `calibration_and_holdout_data` functions for now and perform those aggregations elsewhere. The documentation provides boilerplate code for doing so in SQL:

https://btyd.readthedocs.io/en/latest/Generate%20RFM%20Summaries%20From%20a%20SQL%20Store.html

**Comment by adibbehjat** [comment]
I second the request in terms of updating the SQL example in the documentation as well as it's recording the average across all purchases instead of only the recent purchases. After reading the RFM Summary in Excel document, I noticed Bruce is using 

`=’Pivot Table 2’!B5`

Which reflects only the calibration/repeat column, excluding first purchase
