### ISSUE TITLE
plot_period_transactions after BetaGeoModel().fit()

### ISSUE THREAD

**Issue by DataHurdler** [ColtAllen/btyd#78]
I was trying to plot using `plot_period_transactions` after `BetaGeoModel().fit()` but got an error:

``AttributeError: 'BetaGeoModel' object has no attribute 'data'. Did you mean: '_idata'?``

I tried, but wasn't able to figure out how to plot after `Model()`. Thank you.

**Comment by ColtAllen** [comment]
Hey @zijunluo8620,

Plotting functions aren't currently supported for the `Model` modules at this time; sorry if the documentation suggests otherwise. I'll work on adding plotting support after `BetaGeoCovarModel`, `BetaGeoBetaBinomModel`, and `ParetoNBDModel` are added.

In the meantime though, you can try this for `plot_period_transactions`:

```
from matplotlib import pyplot as plt

# Number of sample datapoints to generate
n = 100
# Maximum customer frequency to consider
max_frequency = 100

simulated_data = BetaGeoModel.generate_rfm_data(size=n)

model_counts = pd.DataFrame(data["frequency"].value_counts().sort_index().iloc[:max_frequency])
simulated_counts = pd.DataFrame(simulated_data["frequency"].value_counts().sort_index().iloc[:max_frequency])
combined_counts = model_counts.merge(simulated_counts, how="outer", left_index=True, right_index=True).fillna(0)
combined_counts.columns = labels

ax = combined_counts.plot(kind="bar", **kwargs)

plt.legend()
plt.title(title)
plt.ylabel(ylabel)
plt.xlabel(xlabel)
```

**Comment by zijunluo8620** [comment]
I ended up taking a similar approach to plot them too. Thank you.
