### ISSUE TITLE
Missing arguments on BetaGeoFitter.fit

### ISSUE THREAD

**Issue by hedgehog-abraxas** [ColtAllen/btyd#80]
Hi!

My name is Antonio and I tried to use you library, I was following the user guide when I tried to use the function BetaGeoFitter().fit(data) i received the following error:

![image](https://user-images.githubusercontent.com/59034821/203396633-8914d26e-1754-4311-9116-a5d6a4da07cf.png)

I went to the code and I see that we can pass the values as a np array so I tried and another error arise:

![image](https://user-images.githubusercontent.com/59034821/203396872-afd966d8-a2fc-4cb8-ba97-99779570f288.png)

**Comment by ColtAllen** [comment]
Hey @hedgehog-abraxas,

(Cool username, by the way.)

This should fix your issue:

```
from btyd import BetaGeoFitter

# Similar API to scikit-learn.
bgm = BetaGeoFitter().fit(frequency = data['frequency'].values, recency = data['recency'].values, T = data['T'].values)
print(bgm)
```

You were passing in Pandas Series objects rather than numpy arrays, which is a common mistake with the legacy `Fitter` models. The new `Model` modules do not have this problem because the entire dataframe is provided in a single argument.

Also, the User Guide should reference `BetaGeoModel` instead of `BetaGeoFitter`, so thanks for pointing that out. I've made the necessary edits to the documentation, which should update in about 24 hours. It's important to note the `Model` classes do not support any of the plotting functions yet, so continue to use `BetaGeoFitter` if you require any diagnostic plots at this time.

**Comment by hedgehog-abraxas** [comment]
Thanks for your answer, it was very helpful. Cheers!
